<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260812160807 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema: users (balance embedded on the user row) and transactions for PicPay Simplificado.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE transactions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, authorization_reference VARCHAR(255) DEFAULT NULL, rejection_reason VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, amount_cents INT NOT NULL, payer_id INT NOT NULL, payee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EAA81A4CC17AD9A9 ON transactions (payer_id)');
        $this->addSql('CREATE INDEX IDX_EAA81A4CCB4B68F ON transactions (payee_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, type VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, balance_updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_number VARCHAR(14) NOT NULL, document_type VARCHAR(4) NOT NULL, balance_cents INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_users_email ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX uniq_users_document_number ON users (document_number)');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4CC17AD9A9 FOREIGN KEY (payer_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4CCB4B68F FOREIGN KEY (payee_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE transactions DROP CONSTRAINT FK_EAA81A4CC17AD9A9');
        $this->addSql('ALTER TABLE transactions DROP CONSTRAINT FK_EAA81A4CCB4B68F');
        $this->addSql('DROP TABLE transactions');
        $this->addSql('DROP TABLE users');
    }
}
